;-------------------------------- PrivateDial ----------------------------------
; Filename: pjsip.conf
; This file is an Asterisk configuration file, part of the PrivateDial suite.
; It is loaded by the chan_pjsip.so module.
;

;-------------------------------- global ---------------------------------------

[global]
type = global
user_agent = Platform PBX

;-------------------------------- includes -------------------------------------

#tryinclude pjsip_transport.conf
; Extension 100
[100]
type=endpoint
context=kam_context
disallow=all
allow=ulaw
transport=simpletrans
auth=auth_100
aors=100

[auth_100]
type=auth
auth_type=userpass
username=100
password=wale

; Extension 101
[101]
type=endpoint
context=kam_context
disallow=all
allow=ulaw
transport=simpletrans
auth=auth_101
aors=101

[auth_101]
type=auth
auth_type=userpass
username=101
password=wale

[kam_context]
type=context

[100]
type=aor
max_contacts=1

[101]
type=aor
max_contacts=1

[simpletrans]
type=transport
protocol=udp
bind=0.0.0.0
