version: '3'

services:
  asterisk-1:
    image: mlan/asterisk
    # network_mode: bridge
    ports:
      - "8080:80"
      - "5060:5060/udp"
      - "5060:5060"
      - "5061:5061"
      - "10000-10099:10000-10099/udp"
    environment:
      - SYSLOG_LEVEL=4
      - HOSTNAME=test1.docker.localhost
      - PULSE_SERVER=unix:/run/pulse/socket
      - PULSE_COOKIE=/run/pulse/cookie
      - WEBSMSD_PORT=80
    volumes:
      - ./asterisk:/usr/share/asterisk/config:ro
      - ./pulse:/run/pulse:rshared
      - /etc/localtime:/etc/localtime:ro
