---
- name: Create freepbx config folder
  file:
    path: "{{ freepbx_deploy_path }}"
    state: directory

- name: Create the FreePBX Server-1
  docker_container:
    name: freepbx-sever-1
    image: tiredofit/freepbx:15-latest
    state: started
    #restart_policy: unless-stopped
    memory: 100M
    memory_swap: 100M
    memory_swappiness: 0
    cpus: 0.3
    ports:
      - "70:80"
      - "444:443"
      - "5160:5160"
      - "4060:5060/udp"
      - "18000-20000:18000-20000/udp"
    env:
      DB_EMBEDDED: "TRUE"
    volumes:
      - "{{ freepbx_deploy_path }}/certs:/certs:ro"
      - "{{ freepbx_deploy_path }}/html:/var/www/html:ro"
      - "{{ freepbx_deploy_path }}/data:/data:ro"

# - name: Copy freepbx config files
#   synchronize:
#     src: freepbx
#     dest: "{{ freepbx_deploy_path }}"
#     archive: no
#     delete: yes
#     recursive: yes
#     checksum: yes
#   notify: Restart freepbx-1

- name: Stop freepbxcontainer
  docker_container:
    name: freepbx-sever-1
    state: stopped
  # when: "'remove_asterisk' in ansible_run_tags or 'tear_down' in ansible_run_tags"
  # tags:
  #   - never
  #   - remove_asterisk
  #   - tear_down
