- name: Update package lists
  apt: update_cache=yes

- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present

- name: Get public IP address
  shell: dig +short myip.opendns.com @resolver1.opendns.com
  register: public_ip
  tags:
   - deploy-kamailio

- name: Install kamailio
  include_tasks: install-kamailio.yaml

- name: Install rtpengine
  apt:
    name:
      - rtpengine
    state: present

- name: Install mysqlclient for Python 3
  apt:
    name: python3-mysqldb
    state: present

- name: Ensure MySQL service is running
  service:
    name: mysql
    state: started
    enabled: yes

- name: copy kamailio.cfg config file
  template:
    src: kamailio.cfg.j2
    dest: /usr/local/etc/kamailio/kamailio.cfg
  tags:
   - deploy-kamailio

- name: copy kamctlrc config file
  template:
    src: kamctlrc.j2
    dest: /usr/local/etc/kamailio/kamctlrc
  tags:
   - deploy-kamailio

- name: copy dispatcher config file
  template:
    src: dispatcher.list.j2
    dest: /usr/local/etc/kamailio/dispatcher.list
  tags:
   - deploy-kamailio

- name: copy rtpengine config file
  template:
    src: rtpengine.conf.j2
    dest: /etc/rtpengine/rtpengine.conf
  tags:
   - deploy-kamailio

- name: copy tls config files
  copy:
    src: "{{ item }}"
    dest: /usr/local/etc/kamailio/{{ item }}
  loop:
    - tls.cfg
    - fullchain.pem
    - privkey.pem
    
  tags:
   - deploy-kamailio

- name: Running kamdbctl create
  command:
    cmd: kamdbctl create
    creates: /var/log/kamailio-db-created

- name: Create kamailio-db-created  flag
  command: touch /var/log/kamailio-db-created
  tags:
   - test

- name: Add subscribers
  command: kamctl add {{ item }} {{ item }}
  args:
    creates: /var/log/subscribers-added
  loop: "{{ subscribers }}"
  tags:
   - test

- name: Create subscribers flag
  command: touch /var/log/subscribers-added
  tags:
   - test

- name: Restart rtpengine service
  ansible.builtin.service:
    name: rtpengine
    state: restarted
  tags:
   - deploy-kamailio

- name: Restart Kamailio service
  ansible.builtin.service:
    name: kamailio
    state: restarted
  tags:
   - deploy-kamailio
