version: '3'

services:
  asterisk-2:
    image: mlan/asterisk
    #network_mode: bridge
    ports:
      - "9080:80"
      - "6060:5060/udp"
      - "6060:5060"
      - "6061:5061"
      - "20000-20099:10000-10099/udp"
    environment:
      - SYSLOG_LEVEL=4
      - HOSTNAME=test2.docker.localhost
      - PULSE_SERVER=unix:/run/pulse/socket
      - PULSE_COOKIE=/run/pulse/cookie
      - WEBSMSD_PORT=80
    volumes:
      - ./asterisk:/usr/share/asterisk/config:ro
      - ./pulse:/run/pulse:rshared
      - /etc/localtime:/etc/localtime:ro
