---
- name: create kamailio config folder
  file:
    path: "{{ kamailio_deploy_path }}"
    state: directory

- name: copy docker-compose.yaml
  copy:
    src: docker-compose.yaml
    dest: "{{ kamailio_deploy_path }}/docker-compose.yaml"

- name: copy kamailio config files
  synchronize:
    src: kamailio
    dest: "{{ kamailio_deploy_path }}"
    archive: no
    delete: yes
    recursive: yes
  notify: restart kamailio

- name: start kamailio
  community.docker.docker_compose:
    project_src: "{{ kamailio_deploy_path }}"
    build: yes

- name: stop and remove kamailio
  docker_compose:
    project_src: "{{ kamailio_deploy_path }}"
    remove_volumes: yes
    state: absent
  when: "'remove_kamailio' in ansible_run_tags or 'tear_down' in ansible_run_tags"
  tags:
    - never
    - remove_kamailio
    - tear_down
