---
- name: create kamailio config folder
  file:
    path: "{{ kamailio_deploy_path }}"
    state: directory

- name: Create the MariaDB container
  docker_container:
    name: kamailio_db
    image: mariadb:latest
    state: started
    restart_policy: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - "./db:/var/lib/mysql"
    env:
      MYSQL_ROOT_PASSWORD: "rootpw"
      MYSQL_DATABASE: "kamailio"
      MYSQL_USER: "kamailio"
      MYSQL_PASSWORD: "kamailiopw"

- name: Create the Kamailio container
  docker_container:
    name: kamailio
    image: ghcr.io/kamailio/kamailio:5.8.1-bookworm
    state: started
    restart_policy: unless-stopped
    ports:
      - "7060:5060/udp"
    volumes:
      - "./kamailio:/etc/kamailio"
    env:
      DBENGINE: "MYSQL"
      DBHOST: "db"
      DBNAME: "kamailio"
      DBRWUSER: "kamailio"
      DBRWPW: "kamailiorw"
      DBROOTUSER: "root"
      DBROOTPW: "rootpw"
      DBUSER: "kamailio"
      DBPW: "kamailiopw"

- name: copy kamailio config files
  synchronize:
    src: kamailio
    dest: "{{ kamailio_deploy_path }}"
    archive: no
    delete: yes
    recursive: yes
  notify: Restart kamailio

- name: stop and remove kamailio
  docker_compose:
    project_src: "{{ kamailio_deploy_path }}"
    remove_volumes: yes
    state: absent
  when: "'remove_kamailio' in ansible_run_tags or 'tear_down' in ansible_run_tags"
  tags:
    - never
    - remove_kamailio
    - tear_down
