---
- name: Create asterisk1 config folder
  file:
    path: "{{ asterisk_deploy_path }}"
    state: directory

- name: Create the Asterisk Server-2
  docker_container:
    name: asterisk2
    image: mlan/asterisk:full-1.1.8
    state: started
    restart_policy: unless-stopped
    ports:
      - "9080:80"
      - "6060:5060/udp"
      - "6060:5060"
      - "6061:5061"
      - "20000-20099:10000-10099/udp"
    env:
      SYSLOG_LEVEL: "4"
      HOSTNAME: "test2.docker.localhost"
      PULSE_SERVER: "unix:/run/pulse/socket"
      PULSE_COOKIE: "/run/pulse/cookie"
      WEBSMSD_PORT: "80"
    volumes:
      - "/home/sip/asterisk2/asterisk:/usr/share/asterisk/config:ro"
      - "/home/sip/asterisk2/pulse:/run/pulse:rshared"
      - "/etc/localtime:/etc/localtime:ro"

- name: Copy asterisk config files
  synchronize:
    src: asterisk
    dest: "{{ asterisk_deploy_path }}"
    archive: no
    delete: yes
    recursive: yes
  notify: Restart Asterisk-2

- name: Stop Asterisk container
  docker_container:
    name: asterisk2
    state: stopped
  when: "'remove_asterisk' in ansible_run_tags or 'tear_down' in ansible_run_tags"
  tags:
    - never
    - remove_asterisk
    - tear_down
